name: Detox iOS

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "ios/**"
      - "e2e/**"
      - "detox.config.*"
      - "package.json"
      - "yarn.lock"
      - "pnpm-lock.yaml"

jobs:
  e2e:
    runs-on: macos-14
    timeout-minutes: 60

    env:
      CI: true
      TERM: xterm
      NODE_OPTIONS: --max_old_space_size=4096
      EXPO_NO_TELEMETRY: 1
      # Ensure the app and Metro agree on the port used for the JS bundle
      RCT_METRO_PORT: 8081

      # --- FE config (from your repository Secrets) ---
      EXPO_PUBLIC_BALANCES_FETCH_INTERVAL: ${{ secrets.EXPO_PUBLIC_BALANCES_FETCH_INTERVAL }}
      EXPO_PUBLIC_DEV_HOST: ${{ secrets.EXPO_PUBLIC_DEV_HOST }}   # e.g. 127.0.0.1:3000
      EXPO_PUBLIC_HOST: ${{ secrets.EXPO_PUBLIC_HOST }}           # e.g. http
      EXPO_PUBLIC_INFURA_ID: ${{ secrets.EXPO_PUBLIC_INFURA_ID }}
      EXPO_PUBLIC_MODE: ${{ secrets.EXPO_PUBLIC_MODE }}
      EXPO_DEV_CLIENT_SCHEME: ${{ vars.EXPO_DEV_CLIENT_SCHEME }}

      # --- Test data (Secrets) ---
      TEST_PIN: ${{ secrets.TEST_PIN }}
      TEST_SEED_PHRASE: ${{ secrets.TEST_SEED_PHRASE }}
      TEST_WALLET_NAME: ${{ secrets.TEST_WALLET_NAME }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.13.1
          run_install: false

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.4
          cache: pnpm

      - name: Select Xcode (prefer 16.4, else best available)
        shell: bash
        run: |
          set -euo pipefail
          candidates=(
            /Applications/Xcode_16.4.app
            /Applications/Xcode_16.4.0.app
            /Applications/Xcode_16.3.app
            /Applications/Xcode_16.3.0.app
            /Applications/Xcode_16.2.app
            /Applications/Xcode_16.2.0.app
            /Applications/Xcode_16.1.app
            /Applications/Xcode_16.1.0.app
            /Applications/Xcode_16.0.app
            /Applications/Xcode_16.0.0.app
            /Applications/Xcode_16.app
            /Applications/Xcode.app
          )
          selected=""
          for x in "${candidates[@]}"; do
            if [ -d "$x" ]; then selected="$x"; break; fi
          done
          if [ -z "$selected" ]; then
            echo "::error::No Xcode installations found under /Applications"
            ls -1 /Applications | sed -n '/Xcode/p' || true
            exit 1
          fi
          echo "Using Xcode at: $selected"
          echo "DEVELOPER_DIR=$selected/Contents/Developer" >> "$GITHUB_ENV"
          DEVELOPER_DIR="$selected/Contents/Developer" xcrun simctl list runtimes || true
          DEVELOPER_DIR="$selected/Contents/Developer" xcrun simctl list devicetypes || true

      - name: Install Apple tools needed by Detox
        run: |
          brew update
          brew tap wix/brew
          brew install applesimutils watchman

      - name: Install JS deps
        run: pnpm install --frozen-lockfile

      # put this AFTER you select Xcode / set DEVELOPER_DIR and AFTER "Install JS deps"
      - name: Build Detox iOS framework cache
        run: |
          npx -y detox@20.40.2 clean-framework-cache || true
          npx -y detox@20.40.2 build-framework-cache

      # Generate/refresh ios/ if it isn't committed. Keep --no-install for speed & caching.
      - name: Expo prebuild (no install)
        run: npx expo prebuild --platform ios --no-install

      # Cache Pods BEFORE install
      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: |
            ios/Pods
            ~/Library/Caches/CocoaPods
            ~/.cocoapods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install CocoaPods
        working-directory: ios
        run: |
          sudo gem install cocoapods -N
          pod install

      - name: Cache DerivedData
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-derived-${{ hashFiles('ios/Podfile.lock', 'ios/**.xcodeproj/**', 'ios/**.xcworkspace/**') }}
          restore-keys: |
            ${{ runner.os }}-derived-

      - name: List simulators (debug aid)
        run: xcrun simctl list devices

      - name: Build app (Detox)
        run: pnpm exec detox build -c ios.sim.debug

      - name: Start Metro (Expo) bundler
        shell: bash
        run: |
          set -euo pipefail
          echo "Starting Metro bundler..."
          PORT="${RCT_METRO_PORT:-8081}"
          STATUS_URL="http://localhost:${PORT}/status"
          # Start Expo (Metro) in background; output goes to metro.log for debugging
          nohup npx expo start --dev-client --no-interactive --clear --port "$PORT" > metro.log 2>&1 &

          echo "Waiting for Metro to be ready on ${STATUS_URL} ..."
          # Give it a brief moment to start
          sleep 3
          # Wait up to ~2 minutes for Metro to report running
          ready="false"
          for i in {1..60}; do
            # Do not let curl failures abort the script; capture output safely
            STATUS=$(curl -fs "$STATUS_URL" || true)
            if echo "$STATUS" | grep -q "packager-status:running"; then
              echo "Metro is running."
              ready="true"
              break
            fi
            sleep 2
          done
          if [ "$ready" != "true" ]; then
            echo "Metro did not become ready in time. Dumping last 200 lines of metro.log for diagnostics:" >&2
            tail -n 200 metro.log || true
            exit 1
          fi

      - name: Run Detox tests (create flow covers setup)
        run: pnpm run e2e:createFlow:tests
